name: tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest  # Utilise une machine virtuelle Ubuntu

    steps:
    - name: Checkout
      uses: actions/checkout@v4  # Récupère le code du dépôt

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"  # Utilise Python 3.10 (adaptez selon votre version)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest httpx pytest-asyncio
        pip install -r api/requirements.txt

    - name: Run tests
      env:
        PYTHONPATH: api
      run: |
        pytest tests/ -v
